graphdb:
  url: "http://localhost:8000/repositories/network/statements"

plugins:
  enabled:
    - name: "mine_sweeper"
      ttl_output: "plugins/mine-sweeper/data/graph_data.ttl"
    - name: "another_plugin"
      ttl_output: "plugins/another-plugin/data/transformed_data.ttl"
  path: "plugins"