FROM ontotext/graphdb:10.6.4

# Add custom setup or configurations, e.g., installing dependencies
# RUN apt-get update && apt-get install -y some-package

# Optional: Copy any necessary files
# COPY ./config/ /opt/graphdb/config/

# Expose ports and set environment variables if needed
EXPOSE 8000
ENV GRAPHDB_HOME=/opt/graphdb/home