services:
  graphdb:
    image: ontotext/graphdb:10.6.4
    container_name: graphdb
    ports:
      - "8000:7200"
    restart: always
    environment:
      - GRAPHDB_HOME=/opt/graphdb/home
    deploy:
      resources:
        limits:
          memory: 4g
          cpus: '2'
    volumes:
      - ./data:/opt/graphdb/data
    networks:
      - graphdb_network

networks:
  graphdb_network:
    driver: bridge