FROM ontotext/graphdb:latest

# Add custom setup or configurations, e.g., installing dependencies
# RUN apt-get update && apt-get install -y some-package

# Optional: Copy any necessary files
# COPY ./config/ /opt/graphdb/config/

# Expose ports and set environment variables if needed
EXPOSE 7200
ENV GRAPHDB_HOME=/opt/graphdb